sudo: required

services:
  - docker

before_install:
  - docker build -t markemp/react-test -f ./client/Dockerfile.dev ./client
  #- docker build -t markemp/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true markemp/react-test npm test

after_success:
  - docker build -t markemp/multi-client ./client
  - docker build -t markemp/multi-nginx ./nginx
  - docker build -t markemp/multi-server ./server
  - docker build -t markemp/multi-worker ./worker
  # Log in to Docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Push images to Docker hub
  - docker push markemp/multi-client
  - docker push markemp/multi-nginx
  - docker push markemp/multi-server
  - docker push markemp/multi-worker
